import Footer from "@/components/common/Footer";
import "./globals.css";
import type { Metadata } from "next";
import Header from "@/components/common/Header";

//FIXME: SEO 활용 나중에 활용해보자
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
